# Generated by Django 5.2.2 on 2025-06-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=255)),
                ('index_tracked', models.CharField(max_length=255)),
                ('aum', models.DecimalField(decimal_places=2, help_text='Assets Under Management in Billions USD', max_digits=15)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('change_1d', models.DecimalField(decimal_places=2, help_text='1-day percentage change', max_digits=10)),
                ('perf_1w', models.DecimalField(decimal_places=2, help_text='1-week percentage change', max_digits=10)),
                ('perf_1m', models.DecimalField(decimal_places=2, help_text='1-month percentage change', max_digits=10)),
                ('perf_3m', models.DecimalField(decimal_places=2, help_text='3-month percentage change', max_digits=10)),
                ('perf_6m', models.DecimalField(decimal_places=2, help_text='6-month percentage change', max_digits=10)),
                ('perf_ytd', models.DecimalField(decimal_places=2, help_text='Year-to-date percentage change', max_digits=10)),
                ('perf_1y', models.DecimalField(decimal_places=2, help_text='1-year percentage change', max_digits=10)),
                ('perf_5y', models.DecimalField(decimal_places=2, help_text='5-year percentage change', max_digits=10)),
                ('perf_10y', models.DecimalField(decimal_places=2, help_text='10-year percentage change', max_digits=10)),
                ('high_52w', models.DecimalField(decimal_places=2, help_text='52-week high price', max_digits=15)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='etf_screener.assets')),
            ],
        ),
        migrations.CreateModel(
            name='AssetZScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('zscore_20d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zscore_100d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zscore_365d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zscore', to='etf_screener.assets')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='etf_screener.assets')),
            ],
            options={
                'verbose_name': 'Asset Price Data',
                'verbose_name_plural': 'Asset Price Data',
                'indexes': [models.Index(fields=['asset', 'date'], name='etf_screene_asset_i_c3bff7_idx')],
            },
        ),
    ]
